#!/bin/sh /etc/rc.common
START=99

start()
{
        if [ ! -f /etc/dropbear/authorized_keys ];
        then
        EC2_KEY=$(wget http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key -q -O -)
            if [ "$EC2_KEY" != "" ];
            then
                echo $EC2_KEY > /etc/dropbear/authorized_keys
                stoptelnet
                startdropbear
            else
                stoptelnet
                startdropbear
            fi
        fi
}

stoptelnet()
{
        /etc/init.d/telnet stop
}

startdropbear()
{
        /etc/init.d/dropbear stop
        /etc/init.d/dropbear start
}

